<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SimpleExcel" nsURI="platform:/resources/com.kaleidoscope.core.aux.simpleexcel/model/SimpleExcel.ecore"
    nsPrefix="SimpleExcel">
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//ExcelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sheet" lowerBound="1" upperBound="-1"
        eType="#//Sheet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sheet" eSuperTypes="#//ExcelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sheetId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sheetName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colobject" lowerBound="1"
        upperBound="-1" eType="#//ColObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowobject" lowerBound="1"
        upperBound="-1" eType="#//RowObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" lowerBound="1" upperBound="-1"
        eType="#//Cell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell" eSuperTypes="#//ExcelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellComments" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RowObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" lowerBound="1" upperBound="-1"
        eType="#//Cell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextRow" eType="#//RowObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" lowerBound="1" upperBound="-1"
        eType="#//Cell"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextColumn" eType="#//ColObject"/>
  </eClassifiers>
</ecore:EPackage>
