<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SimpleExcel" nsURI="platform:/plugin/SimpleExcel/model/SimpleExcel.ecore"
    nsPrefix="SimpleExcel">
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//ExcelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sheet" lowerBound="1" upperBound="-1"
        eType="#//Sheet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folder" eSuperTypes="#//ExcelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" upperBound="-1" eType="#//File"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentFolder" lowerBound="1"
        eType="#//Folder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFolder" upperBound="-1"
        eType="#//Folder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sheet" eSuperTypes="#//ExcelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sheetId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sheetName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colobject" lowerBound="1"
        upperBound="-1" eType="#//ColObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowobject" lowerBound="1"
        upperBound="-1" eType="#//RowObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell" eSuperTypes="#//ExcelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="foregroundColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cellComments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExcelElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RowObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" lowerBound="1" upperBound="-1"
        eType="#//Cell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isheader" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" lowerBound="1" upperBound="-1"
        eType="#//Cell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
